name: GKCore
main: me.GK.core.main.GKCore
version: 3.1.5
api-version: 1.13
softdepend: [MySQL]
description: A Core plugin for a set of plugins made by GKPixel.
author: G7
commands:
 gk:
  description: testing