# Do NOT touch configVersion, used for internal purposes
configVersion: 0
overrideMessages: true
debugMode: false
lobbyName: mlobby
languages: [ en-US, zh-TW ]
testkey: test
Buttons:
  PreviousPage:
    ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §a<<<
  NextPage:
    ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §a>>>
  Back:
    ==: org.bukkit.inventory.ItemStack
    type: WOOL
    damage: 14
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §cBack