debugMode: false
Messages:
  systemName: '&8【&aGKCore&8】'
  startListeningInput: "&aplease enter the string. &etype &ccancel &eto cancel"
  cancelledSuccessfully: "&acancelled input detection successfully"
  topSplitter: '&e------------------------------------'
  editorNameLine: "&e--------------&6[%name%&6]&e---------------"
  bottomSplitter: '&e------------------------------------'
  addSign: "&a[+]"
  removeSign: "&c[X]"
  backSign: "&6[<--]"
  days: "&edays"
  hours: "&ehour"
  minutes: "&eminutes"
  seconds: "&eseconds"
  remainingTime: "&cremaining time: %time%"
  display: "&eDisplay"
  lore: "&eLore"
  copy: "&a[Copy]"
  copiedLore: "&acopied lore"
  paste: "&b[Paste]"
  lorePin: " &e-&f "
  price: "&ePrice"
  cooldown: "&eCooldown"
  mana: "&bMana"
  changeItemStack: "&e[change ItemStack to your main hand Item]"
  edit: "&eEdit"
  back: "&cBack"
  add: "&eAdd"
  remove: "&cRemove"
  clickToChangeItemStack: "&b[clickToChangeItemStack]"
  clickToGetItemStack: "&b[Get]"
  loreEditor: "&eLore Editor"
  buttonEditorName: "&aButton Editor"
  buttonIDLore: "&6[&b%buttonID%&6]"
  cannotSetButtonError: "&4Cannot set button &c[Reason: no item in hand]"
  leftClickToEdit: "&aLeft Click: &eEdit"
  dragItemToReplace: "&aDrag Item: &eReplace"
  useBracketWithPlaceholder: "&6remember to use bracket with your placeholder like this &a&l{gkdata_money}"
  databaseTransferFailedBecauseAlreadyIs: "&bYou are already using this database type! Cannot transfer.."
  cancelButton: "&7[&cCancel&7]"
  cancelHover: "&7cancel the editor"
  cloneButton: "&7[&bClone&7]"
  cloneHover: "&7clone from original"
  errorHaventFinishedLoading: "&c[Error] &aNot yet finished loading"
helpList:
- ---------------------------------------------------
- "&6/gk version &7show the GKCore version"
- "&6/gk help &7show help list"
- "&6/gk info &7show all GK plugins info"
- "&6/gk placeholder &6&l<placeholder> &7check self placeholder"
- "&6/gk placeholder &6&l<player> <placeholder> &7check player's placeholder"
- "&6/gk reloadAllPlugins &7reload all GK plugins"
- "&6/gk setDisplay &7(Edit the display name of item in main hand)"
- "&6/gk editLore &7(Edit the lore of item in main hand)"
lobbyName: mlobby
testkey: test
Buttons: 
  PreviousPage:
    ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §a<<<
  NextPage:
    ==: org.bukkit.inventory.ItemStack
    type: ARROW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §a>>>
  Back:
    ==: org.bukkit.inventory.ItemStack
    type: WOOL
    damage: 14
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §cBack